 [[redirects]]
  from = "/Projects"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/contact"
  to = "/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"